# Generated by Django 4.0.2 on 2022-04-12 10:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
