# Generated by Django 4.0.2 on 2022-04-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_foodpost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='n.jpg', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
